[project]
name = "vand2025_eval"
version = "0.1.0"
description = "VAND 2025 evaluation script"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anomalib[full]",
    "cython==0.29.36",
    "editables>=0.5",
    "eigen>=0.1.1",
    "hatchling>=1.27.0",
    "pydensecrf>=1.0rc3",
    "scikit-learn",
    "setuptools==76.1.0",
]

[tool.uv.sources]
anomalib = { git = "https://github.com/openvinotoolkit/anomalib.git", branch = "main" }


[tool.hatch.build.targets.wheel]
packages = ["src/eval"]

[project.scripts]
eval = "eval.evaluate:eval"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
no-build-isolation-package = ["pydensecrf"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.ruff.lint.isort]
known-first-party = ["eval"]


