name: Evaluation Workflow

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - "src/eval/submission/**"

jobs:
  security-check:
    name: Security Check
    runs-on: vand2025-runner
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run Zizmor security scan
        run: |
          uv tool install zizmor
          uvx zizmor --config zizmor.yml .github/workflows/evaluate.yaml

  evaluate:
    needs: security-check
    runs-on: vand2025-runner
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout PR code for evaluation
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
      - name: Save PR User and Number
        env:
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_NAME: ${{ github.event.pull_request.title }}
        run: |
          echo $PR_USER > pr_user.txt
          echo $PR_NUMBER > pr_number.txt
          echo $PR_NAME > pr_name.txt
      - name: Run evaluation
        timeout-minutes: 300 # 5 hours timeout
        run: |
          GIT_LFS_SKIP_SMUDGE=1 uv sync
          uv run eval --dataset_path=/home/user/datasets/mvtec_loco
      - name: Upload evaluation results and SHA
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-results
          path: |
            results.json
            metrics.csv
            pr_user.txt
            pr_number.txt
            pr_name.txt
          retention-days: 30
